name: CD

on:
  push:
    branches:
    - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to GCP
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
            cd Cyberlove/backend
            git pull
            npm ci
            pm2 restart backend

